database_path: "./LA/"
asv_score_path: "/home/eoil/sasv-joint-optimisation/protocols/ASVspoof2019.LA.asv.eval.gi.trl.txt"
model_path: "/home/eoil/aasist/models/weights/AASIST.pth"
batch_size: 1
num_epochs: 100
loss: "CCE"
track: "LA"
eval_all_best: true
eval_output: "eval_scores_using_best_dev_model.txt"
cudnn_deterministic_toggle: true
cudnn_benchmark_toggle: false
model_config:
  architecture: "AASIST"
  nb_samp: 64600
  first_conv: 128
  filts: [70, [1, 32], [32, 32], [32, 64], [64, 64]]
  gat_dims: [64, 32]
  pool_ratios: [0.5, 0.7, 0.5, 0.5]
  temperatures: [2.0, 2.0, 100.0, 100.0]
optim_config:
  optimizer: "adam"
  amsgrad: false
  base_lr: 0.0001
  lr_min: 0.000005
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  scheduler: "cosine"
